import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

const TermsOfService = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-1 pt-24 pb-16 px-8">
        <div className="container mx-auto max-w-4xl">
          <h1 className="font-display text-5xl font-bold text-heritage-burgundy mb-8 text-center">
            Terms of Service
          </h1>
          
          <div className="bg-heritage-cream p-12 rounded-lg border-4 border-heritage-gold shadow-lg">
            <p className="font-body text-heritage-brown/70 mb-8 italic">
              Last Updated: January 2025
            </p>
            
            <div className="space-y-8 font-body text-lg leading-relaxed text-heritage-brown/90">
              <p>
                Welcome to YantraVeda. These Terms of Service ("Terms") govern your use of the YantraVeda website and the services provided therein. By accessing or using our website, you agree to be bound by these Terms.
              </p>
              
              <section>
                <h2 className="font-heading text-3xl font-bold text-heritage-burgundy mb-4">
                  1. Intellectual Property
                </h2>
                <p>
                  All content published and made available on our site, including but not limited to text, logos, graphics, 3D models, and the dimensional data generated by our calculation engine, is the property of YantraVeda and its creators. This material is protected by copyright and other intellectual property laws. We grant you a limited, non-exclusive, non-transferable license to use the site and its content for personal, non-commercial, and educational purposes only.
                </p>
              </section>
              
              <section>
                <h2 className="font-heading text-3xl font-bold text-heritage-burgundy mb-4">
                  2. User Accounts
                </h2>
                <p className="mb-3">When you create an account on our site, you agree to the following:</p>
                <ul className="list-disc pl-8 space-y-2">
                  <li>You are solely responsible for your account and the security of your password.</li>
                  <li>All personal information you provide to us is accurate and up-to-date.</li>
                  <li>We reserve the right to suspend or terminate your account if you violate these Terms or use our site for illegal or abusive purposes.</li>
                </ul>
              </section>
              
              <section>
                <h2 className="font-heading text-3xl font-bold text-heritage-burgundy mb-4">
                  3. Acceptable Use
                </h2>
                <p className="mb-3">
                  You agree not to use the YantraVeda website for any unlawful purpose or any purpose prohibited under this clause. You agree not to:
                </p>
                <ul className="list-disc pl-8 space-y-2">
                  <li>Harass or mistreat other users.</li>
                  <li>Violate the intellectual property rights of the site owners or any third party.</li>
                  <li>Attempt to hack, reverse-engineer, or otherwise disrupt the security and integrity of the service.</li>
                </ul>
              </section>
              
              <section>
                <h2 className="font-heading text-3xl font-bold text-heritage-burgundy mb-4">
                  4. Disclaimer of Warranties & Limitation of Liability
                </h2>
                <p className="mb-4">
                  The YantraVeda platform is provided for educational and informational purposes only. While we strive for the highest degree of historical and mathematical accuracy, the calculations and data are provided on an "as is" basis without any warranties, express or implied.
                </p>
                <p>
                  YantraVeda and its creators will not be liable for any actions, claims, losses, or damages arising from your use of the site or your reliance on the information it provides. The dimensions generated are for academic and visualization purposes and should not be used for actual construction or navigation without verification by a qualified expert.
                </p>
              </section>
              
              <section>
                <h2 className="font-heading text-3xl font-bold text-heritage-burgundy mb-4">
                  5. Links to Other Websites
                </h2>
                <p>
                  Our site contains links to third-party websites that we do not own or control. We are not responsible for the content, policies, or practices of any third-party website. It is your responsibility to read the terms and conditions and privacy policies of these third-party sites.
                </p>
              </section>
              
              <section>
                <h2 className="font-heading text-3xl font-bold text-heritage-burgundy mb-4">
                  6. Termination
                </h2>
                <p>
                  We may terminate or suspend your access to our service at any time, without prior notice or liability, for any reason, including a breach of these Terms.
                </p>
              </section>
              
              <section>
                <h2 className="font-heading text-3xl font-bold text-heritage-burgundy mb-4">
                  7. Governing Law
                </h2>
                <p>
                  These Terms and Conditions are governed by applicable laws.
                </p>
              </section>
              
              <section>
                <h2 className="font-heading text-3xl font-bold text-heritage-burgundy mb-4">
                  8. Changes to These Terms
                </h2>
                <p>
                  We reserve the right to amend these Terms at any time. We will notify users of changes by posting a notice on our site. Your continued use of the website after such changes constitutes your acceptance of the new Terms.
                </p>
              </section>
              
              <section>
                <h2 className="font-heading text-3xl font-bold text-heritage-burgundy mb-4">
                  9. Contact Us
                </h2>
                <p>
                  If you have any questions about these Terms of Service, please contact us at:{" "}
                  <a href="mailto:sankar.chaitanya2025@gmail.com" className="text-heritage-bronze hover:text-heritage-gold transition-colors underline">
                    sankar.chaitanya2025@gmail.com
                  </a>
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default TermsOfService;
